poll/urls.py
from django.urls import path
from . import views

app_name = 'poll'
urlpatterns = [
path('',views.IndexView.as_view(),name="Home_page"),
path('<int:pk>/',views.DetailView.as_view(),name="detail"),
path('<int:pk>/results', views.ResultsView.as_view(), name='results'),
path('<int:question_id>/vote', views.vote, name='vote'),
]

poll/models.py
from django.db import models
from django.utils import timezone
import datetime

class Question(models.Model):

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('Published Date')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

poll/views.py
from django.http import Http404,HttpResponse,HttpResponseRedirect
from .models import Question,Choice
from django.shortcuts import render,get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone

class IndexView(generic.ListView):
    template_name = 'poll/index.html'
    context_object_name = 'latest_q_list'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'poll/detail.html'

    def get_queryset(self):

        return Question.objects.filter(pub_date__lte = timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'poll/results.html'


def vote(request,question_id):
    question = Question.objects.get(pk=question_id)
    try:
        print(request.POST['choice'])
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError,Choice.DoesNotExist):
        return render(request, "poll/detail.html", {'error_message':"You didn't select a choice.",'question':question})
    else:
        selected_choice.votes+=1
        selected_choice.save()
        return HttpResponseRedirect(reverse('poll:results', args=(question.id,)))

poll/templates/poll/detail.html
{% if question %}

    <h1>{{ question.question_text }}</h1>

    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    <form action="{% url 'poll:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id='choice{{ forloop.counter }}' value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}

        <input type="submit" value="vote">
    </form>

{% endif %}

poll/templates/poll/index.html
{% load static %}
<link rel="stylesheet" href={% static 'poll/styles.css' %}>

{% if latest_q_list %}

    <ul>
        {% for question in latest_q_list %}
            <li><a href="{% url 'poll:detail' question.id%}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>

{% else %}
    <p>No polls are available.</p>

{% endif %}

poll/templates/poll/results.html
<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
        <li>
        {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}
        </li>
    {% endfor %}
</ul>

<a href="{% url 'poll:detail' question.id %}">Vote Again?</a>